### ISSUE TITLE
angular-smart-chartist's tooltip attribute is conflicting with the tooltip attribute used by ui-angular-bootstrap

### ISSUE THREAD

**Issue by xpingfighter** [leftstick/angular-smart-chartist#1]
I've installed angular-smart-chartist along with angular-bootstrap and the two don't play nicely together.  Recommend prefixing angular-smartist-chartist tooltip, so it's something like ngscTooltip.

**Comment by leftstick** [comment]
A prefix is good to be used to avoid conflict. Fixed in version `1.3.3`

**Comment by xpingfighter** [comment]
Great, thanks!
