### ISSUE TITLE
tooltip position

### ISSUE THREAD

**Issue by benavern** [leftstick/angular-smart-chartist#2]
Hello, 

I'd be interrested in your directive because of the tooltip hability but it doesn't wor well i think because the tooltips are not positionned on the point the mouse hovers but always on the top left corner.

![capture](https://cloud.githubusercontent.com/assets/5999900/6389644/1e947448-bda6-11e4-8d8c-89e7bfed3d49.PNG)

could you please provide me a fix for that ?

**Comment by leftstick** [comment]
I haven't seen such a issue, can you provide more information on it? Like what browser you're using? Better if you could give a plunker

**Comment by benavern** [comment]
I just cloned your repo, installed dependencies and launched the server.
It happened on Firefox up to date and on each type of charts. 
I ended up choosing an other tool: chartjs with an angular directive available on github too. Thank you for answering me though ;-)

**Comment by leftstick** [comment]
The issue caused by the `offsetX/Y` attribute which doesn't exist in FF. Fixed at version `1.3.4`. Welcome give a try with the new version. Or you can visit http://leftstick.github.io/angular-smart-chartist/ for a quick view
